ASP.NET Core/StockControl/src/StockControl/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessServices;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace StockControl.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBusinessService _businessService;
        private readonly ILogger<HomeController> _log;

        public HomeController(IBusinessService businessService, ILogger<HomeController> log)
        {
            _businessService = businessService;
            _log = log;
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public IActionResult Index()
        {
            //int w = 0;
            //int q = 1 / w;
            _log.LogInformation("This is Index View!");          
            //return View(_businessService.GetTop5Stocks().ToList());            
            return View();
            
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public IActionResult GetTopStocks()
        {            
            ModelState.Clear();
                        
            //return this.PartialView("TopStocks", _businessService.GetTop5Stocks().ToList());
            return ViewComponent("TopStocks");
        }

        public IActionResult Details(int? id)
        {
            //return View();

            //return ViewComponent("CompanyDetails", new { CompanyID = id } );
            ViewBag.id = id;
            return View("Details");
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public IActionResult AllStocks()
        {
            ModelState.Clear();
            //To check data passing
            //ViewBag.ViewC = "1234566778";
            //ViewBag.SessionData = HttpContext.Session.GetString("SessionData");
            return View("AllStocks");
        }


        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public IActionResult AllStocksComponent()
        {
            ModelState.Clear();
            //To check data passing
            //HttpContext.Session.SetString("SessionHome", "This is Session Data from HomeController");
            return ViewComponent("AllStocks");
        }
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ASP.NET Core/StockControl/src/StockControl/ViewComponents/AllStocksViewComponent.cs
using BusinessServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockControl.ViewComponents
{
    public class AllStocksViewComponent : ViewComponent
    {
        private readonly IBusinessService _businessService;

        public AllStocksViewComponent(IBusinessService businessService)
        {
            _businessService = businessService;
        }

        public IViewComponentResult Invoke()
        {
            //To check data passing
            //ViewBag.VC = "VC test Data from Component.cs";
            //HttpContext.Session.SetString("SessionData", "This is Session Data");

            //ViewBag.SessionHome = HttpContext.Session.GetString("SessionHome");

            return View(_businessService.GetAllStocks().ToList());
        }
    }
}

ASP.NET Core/StockControl/src/StockControl/ViewComponents/CompanyDetailsViewComponent.cs
using BusinessServices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockControl.ViewComponents
{
    public class CompanyDetailsViewComponent : ViewComponent
    {
        private readonly IBusinessService _businessService;

        public CompanyDetailsViewComponent(IBusinessService businessService)
        {
            _businessService = businessService;
        }

        public IViewComponentResult Invoke(int CompanyID)
        {
            return View(_businessService.GetCompanyInfo(CompanyID));
        }
    }
}
  

ASP.NET Core/StockControl/src/StockControl/ViewComponents/TopStocksViewComponent.cs
using BusinessServices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockControl.ViewComponents
{
    public class TopStocksViewComponent : ViewComponent
    {
        private readonly IBusinessService _businessService;

        public TopStocksViewComponent(IBusinessService businessService)
        {
            _businessService = businessService;
        }

        public IViewComponentResult Invoke()
        {
            return View(_businessService.GetTop5Stocks().ToList());
        }
        
    }
}

ASP.NET Core/StockControl/src/StockControl/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ASP.NET Core/StockControl/src/StockControl/Views/Home/AllStocks.cshtml
@model IEnumerable<BusinessEntities.CompanyStockModel>

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<head>

    <meta name="viewport" content="width=device-width" />



    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>

<div class="row" id="AllStocksSection">
    @await Component.InvokeAsync("AllStocks")
</div>
<div>
    @*To check data passing*@
    @*Data from View: @ViewBag.ViewC <br />
    Data from View Component: @ViewBag.VC <br />
    Data from Session:@ViewBag.SessionData*@

</div>
    <div>
        <a asp-action="Index"><b>Back to Home Page</b></a>
    </div>

    <script type="text/javascript">

        $(function () {

            setInterval(function () { $('#AllStocksSection').load('/Home/AllStocksComponent'); }, 3000);

        });
    </script>

ASP.NET Core/StockControl/src/StockControl/Views/Home/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@*To test caching*@
@*<cache vary-by-route="id">
    @{System.Threading.Thread.Sleep(5000); }
</cache>*@

<div>
    <div id="CompanyDetailsSection">
        @{
            var id = ViewBag.id;
        }

        @await Component.InvokeAsync("CompanyDetails", new { CompanyID = id })
    </div>

    <div>        
        <a asp-action="Index"><b>Back to Home Page</b></a>
    </div>

</div>

ASP.NET Core/StockControl/src/StockControl/Views/Home/Index.cshtml
@model IEnumerable<BusinessEntities.CompanyStockModel> 

@{
    ViewData["Title"] = "Home Page";
}

<head>
<meta name="viewport" content="width=device-width" />    
<script src="~/lib/jquery/dist/jquery.js"></script>
</head>

    
    <div>
        <div id="TopStocksSection">

            @*@Html.Partial("TopStocks")*@

            @await Component.InvokeAsync("TopStocks")

        </div>
    </div>
      
    <div>
        <a asp-action="AllStocks"><b>All Stocks</b></a>
    </div>

@*</div>*@

<script type="text/javascript">
    
    $(function () {
        
        setInterval(function () { $('#TopStocksSection').load('/Home/GetTopStocks'); }, 3000);
                
    });
</script>

ASP.NET Core/StockControl/src/StockControl/Views/Home/TopStocks.cshtml
@model IEnumerable<BusinessEntities.CompanyStockModel>


@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-md-3">
        <h2>Top 5 Stocks - from Partial View</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CompanyName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StockPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.GainPercentage)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompanyName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GainPercentage)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

ASP.NET Core/StockControl/src/StockControl/Views/Shared/Components/AllStocks/Default.cshtml
@model IEnumerable<BusinessEntities.CompanyStockModel>

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="row">
    <div class="col-md-3">
        <h2>All Stocks</h2>
        @*To check data passing*@
        @*<div>@ViewBag.VC <br /> @ViewBag.SessionHome</div>*@
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CompanyName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StockPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.GainPercentage)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.CompanyID">@Html.DisplayFor(modelItem => item.CompanyName)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GainPercentage)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

ASP.NET Core/StockControl/src/StockControl/Views/Shared/Components/CompanyDetails/Default.cshtml
@model BusinessEntities.CompanyStockModel


@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-md-3" style="width:600px !important">
        <h2>Company Information: @Html.DisplayFor(model => model.CompanyName)</h2>
        <table class="table">  
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CompanyName)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Description)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.CEOName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CEOName)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.OfficeAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.OfficeAddress)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.EmailID)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.EmailID)
                    </td>
                </tr>
            </tbody>
</table>
    </div>
</div>

ASP.NET Core/StockControl/src/StockControl/Views/Shared/Components/TopStocks/Default.cshtml
@model IEnumerable<BusinessEntities.CompanyStockModel>


@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-md-3">
        <h2>Top Stocks</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CompanyName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StockPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.GainPercentage)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                           <a asp-action="Details" asp-route-id="@item.CompanyID">@Html.DisplayFor(modelItem => item.CompanyName)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GainPercentage)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

ASP.NET Core/StockControl/src/StockControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockControl</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">StockControl</a>
                

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li> 
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div>
                
                    <environment names="Development">
                        &copy; 2017 - StockControl
                        - Development
                    </environment>

                    <environment names="Staging">
                        &copy; 2017 - StockControl
                        - Staging
                    </environment>
               
            </div>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>