ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebDeploy.Models
{
    public class Employee
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
       // public string DateOfBirth { get; set; }
       // public Gender Gender { get; set; }
       // public IList<string> EducationList { get; set; }
       // public int DepartmentId { get; set; }
    }
    public enum Gender
    {
        Male = 0,
        Female = 1
    }
}

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebDeploy.Models
{
    public class Product
    {
        public string Name { get; set; }
        public string Sales { get; set; }
        public string Price { get; set; }
        
    }
}

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebDeploy.Models;
using WebDeploy.Helper;
using WebDeploy.ServiceAgent;
using WebDeploy.Models;

namespace WebDeploy.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServiceAgent _serviceAgent;

        public HomeController(IServiceAgent serviceAgent)
        {
            _serviceAgent = serviceAgent;

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
        [HttpPost]
        public Employee SaveEmployee([FromBody] Employee emp)
        {
            //Save Employee here
            return emp;
        }

        public IActionResult Test()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
            //return RedirectToAction("Index1", "Redirect");
        }
        public List<Product> GetAllData()
        {
            return _serviceAgent.GetAllProducts();
        }

    }
}

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Controllers/RedirectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebDeploy.ServiceAgent;
using WebDeploy.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebDeploy.Controllers
{
    public class RedirectController : Controller
    {
        private readonly IServiceAgent _serviceAgent;

        public RedirectController(IServiceAgent serviceAgent)
        {
            _serviceAgent = serviceAgent;
           
        }// GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public List<Product> GetAllData()
        {
            return _serviceAgent.GetAllProducts();
        }
        public IActionResult ShowLiveTime()
        {
            return View();
        }
        public List<Product> GetPriceData()
        {
            return _serviceAgent.GetPrice();
        }
    }
}

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<script src="@Url.Content("~/lib/jquery/dist/jquery.js")"></script>
<script src="@Url.Content("~/lib/knockout/dist/knockout.js")"></script>
<script src="@Url.Content("~/lib/knockout/dist/knockout.simpleGrid.3.0.js")"></script>
<script src="@Url.Content("~/js/Refresh.js")"></script>
<link href="~/css/gird.css" rel="stylesheet" />

<h2>@ViewData["Title"].</h2>
<div style="padding:10px">
    <div>
        Product Name:<br>
        <input type="text" id="txtProductName" name="txtProductName" data-bind="value:Product.name" />
    </div>
    <div>
        Sales Count:<br>
        <input type="text" id="txtSalesCount" name="txtSalesCount" data-bind="value:Product.sales" />
    </div>
    <div>
        Price:<br>
        <input type="text" id="txtFullName" name="txtFullName" data-bind="value:Product.price" />
    </div>
    <br>
    <button data-bind='click: addItem'>
        Add Product
    </button>
    <br>
</div>
<div data-bind='simpleGrid: gridViewModel'> </div>
<button data-bind='click: sortByName'>
    Sort By Name
</button>
<button data-bind='click: jumpToFirstPage, enable: gridViewModel.currentPageIndex'>
    First Page
</button>

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Home/Test.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<script src="@Url.Content("~/lib/jquery/dist/jquery.js")"></script>
<script src = "@Url.Content("~/lib/knockout/dist/knockout.js")"></script>
<script src="@Url.Content("~/js/employee.js")"></script>

<h3>Employee Form</h3>
<div style="padding:10px">
    <form id="employeeForm" name="employeeForm" method="post">
        <p>
            <label class="form-label">First Name:</label>
            <input type="text" id="txtFirstName" name="txtFirstName" data-bind="value:Employee.FirstName" />
        </p>
        <p>
            <label class="form-label">Last Name:</label>
            <input type="text" id="txtLastName" name="txtLastName" data-bind="value:Employee.LastName" />
        </p>
        <p>
            <label class="form-label">Full Name:</label>
            <input type="text" id="txtFullName" name="txtFullName" data-bind="value:Employee.FullName" readonly="readonly" />
        </p>
             <input type="button" id="btnSubmit" value="Submit" data-bind="click: submit" />
            <input type="button" id="btnReset" value="Reset" data-bind="click: reset" />
</form>
</div>

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Redirect/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<script src="@Url.Content("~/lib/jquery/dist/jquery.js")"></script>
<script src="@Url.Content("~/lib/knockout/dist/knockout.js")"></script>
<script src="@Url.Content("~/js/task.js")"></script>
<link href="~/css/gird.css" rel="stylesheet" />
<b>Click on cell to edit</b>

<table style="padding:2px; border:1px solid gray; width:400px">
    <thead>
        <tr style="padding:2px;border:1px solid gray">  @*data-bind="foreach: columns*@
            <th>Name</th>@*data-bind="text: $data"*@
            <th>Sales</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody  data-bind="foreach: { data: items, as: 'item'}">
        <tr data-bind="foreach: $parent.columns">
            <td style="padding:2px;" data-bind="template: { name: item.templateToUse }, event:{click:item.selectCell}"> </td>
        </tr>
    </tbody>
</table>

@*<pre data-bind="text: ko.toJSON($root, null, 2)"></pre>*@

<script id="read" type="text/html">
    <div data-bind="text: item[$data]"></div>
</script>

<script id="write" type="text/html">
        <input type="text" data-bind="value: item[$data]" />
    </script>

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Redirect/ShowLiveTime.cshtml
@{
    ViewData["Title"] = "Show Live Time";
}
<script src="@Url.Content("~/lib/jquery/dist/jquery.js")"></script>
<script src="@Url.Content("~/lib/knockout/dist/knockout.js")"></script>
<script src="@Url.Content("~/lib/knockout/dist/knockout.simpleGrid.3.0.js")"></script>
<script src="@Url.Content("~/js/time.js")"></script>
<link href="~/css/gird.css" rel="stylesheet" />
<h3>
    <span data-bind="text: TimeString">Start...</span>
</h3>
<h4>
    <span >Price Updates : </span>
</h4>
<div>
    Name:<span data-bind="text: Name">Name...</span><br>
    Sales:<span data-bind="text: Sales">Sales...</span><br>
    Price:<span data-bind="text: Price">Price...</span>
</div>

ASP.NET Core/KnockoutAspNetCore/src/WebDeploy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebDeploy</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebDeploy</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @*<li><a asp-area="" asp-controller="Redirect" asp-action="Index">EditGrid</a></li>*@
                    <li><a asp-area="" asp-controller="Redirect" asp-action="ShowLiveTime">Live Time</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Test">PostData</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - WebDeploy</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>